[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = {version = "=1.0.188", features = ["derive"] }

[dev-dependencies]
serde_json = { version = "1.0.105", features = [] }
